

baseUrl: https://data.sfgov.org/resource/
socrata_config_fn: /Users/j9/Desktop/metadata-explorer-api/configs/socrata_config.yaml
fbfs:
  datasetProfiles:
    fbf: 8ez2-fksg
    fields: [datasetid, nbeid, record_count, field_count, documented_count, documented_percentage, global_field_count, global_field_percentage, days_since_last_updated, days_since_first_created, department]
    idField: datasetid
    qryParams:
  assetInventory:
    fbf: c8w6-4ptn
    fields: [category, creation_date, data_change_frequency, data_notes,data_provided_by, description, geographic_unit, keywords, type, last_update_date_data, license, name, owner, publishing_frequency]
    idField: u_id
    qryParams:
  master_dd:
    fbf: 8zp7-ik63
    fields: [data_dictionary_attached,  attachment_url]
    idField: datasetid
    qryParams: limit 1

